apiVersion: v1
kind: Service
metadata:
  name: continuous-test-demo
  labels:
    app: continuous-test-demo
spec:
  type: LoadBalancer
  selector:
    app: continuous-test-demo
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP